### PR TITLE
external/e2fsprogs: fix build with newer/patched glibc

### PR DESCRIPTION
**Pull request by sarnold**
This is required for updated build host, depending on the glibc version/patches applied.

Change-Id: I6baa8a9fd1c9559310bfa2a63731f882135f89af
Signed-off-by: Steve Arnold <nerdboy@gentoo.org>

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM

**Comment by Flohack74** [comment]
Can we merge this? @ricmm

**Comment by Flohack74** [comment]
@mariogrip @ricmm Can we merge this?

**Review by UniversalSuperBox — APPROVED** [review]
Builds hammerhead, bacon, and FP2 on gcc-9.

**Pull request merged**
